# Generated by Django 6.1 on 2026-08-19 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_car_photo_car_plate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='photo',
        ),
    ]
